import type {
  ActivityLog,
  Campaign,
  Category,
  Client,
  FormDefinition,
  Lead,
  Script
} from "@/lib/types";

const now = "2026-04-17T16:30:00.000Z";

export const mockClients: Client[] = [
  {
    id: "client-mikes-auto",
    name: "Mike's Auto Repair",
    niche: "Auto Repair",
    contactPerson: "Mike Reynolds",
    phone: "+1 647-555-0140",
    email: "mike@mikesauto.example",
    notes: "Primary Ontario mechanic account. Wants more quote requests and repeat service reminders.",
    status: "active",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "client-northstar-realty",
    name: "Northstar Realty Group",
    niche: "Real Estate",
    contactPerson: "Sara Khan",
    phone: "+1 416-555-1002",
    email: "sara@northstar.example",
    notes: "Needs inbound seller leads and a follow-up system for old inquiry lists.",
    status: "active",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "client-zen-spa",
    name: "Zen Mobile Auto Spa",
    niche: "Car Detailing",
    contactPerson: "Omar Lee",
    phone: "+1 705-555-6042",
    email: "omar@zenmobile.example",
    notes: "Visual service business. Strong before/after offer angles.",
    status: "active",
    createdAt: now,
    updatedAt: now
  }
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp-mike-instant",
    clientId: "client-mikes-auto",
    name: "Instant Form Leads",
    source: "Meta Instant Forms",
    description: "Cold inbound leads asking for quotes or service offers.",
    nicheContext: "Auto repair service quote lead flow",
    defaultStage: "New",
    defaultScriptId: "script-auto-first",
    status: "active",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "camp-mike-facebook",
    clientId: "client-mikes-auto",
    name: "Facebook Leads",
    source: "Facebook Outreach",
    description: "Manual outreach and ad-driven conversations from Facebook.",
    nicheContext: "Auto shop outbound and social responses",
    defaultStage: "Contacted",
    defaultScriptId: "script-auto-follow",
    status: "active",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "camp-mike-missed-calls",
    clientId: "client-mikes-auto",
    name: "Missed Call Leads",
    source: "Missed Calls",
    description: "Hot intent missed-call follow-up flow.",
    nicheContext: "High urgency missed call recovery",
    defaultStage: "Replied",
    defaultScriptId: "script-auto-objection",
    status: "active",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "camp-realty-reactivation",
    clientId: "client-northstar-realty",
    name: "Reactivation",
    source: "Old CRM List",
    description: "Old inquiry list being reactivated with a fresher angle.",
    nicheContext: "Real estate lead reactivation",
    defaultStage: "New",
    defaultScriptId: "script-realty-reactivation",
    status: "active",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "camp-zen-brake-offer",
    clientId: "client-zen-spa",
    name: "Seasonal Offer Campaign",
    source: "CSV Import",
    description: "Seasonal promo list for detailing and package upgrades.",
    nicheContext: "Detailing promo and visual content offer",
    defaultStage: "New",
    defaultScriptId: "script-detailing-offer",
    status: "active",
    createdAt: now,
    updatedAt: now
  }
];

export const mockCategories: Category[] = [
  { id: "cat-auto", name: "Auto Repair", color: "#f4be49", rules: ["repair", "mechanic", "auto", "garage"] },
  { id: "cat-tire", name: "Tire Shop", color: "#68aefc", rules: ["tire", "wheel", "alignment"] },
  { id: "cat-detailing", name: "Car Detailing", color: "#46d3a2", rules: ["detail", "spa", "wash", "ceramic"] },
  { id: "cat-realty", name: "Real Estate", color: "#ad88ff", rules: ["realty", "broker", "homes", "estate"] }
];

export const mockScripts: Script[] = [
  {
    id: "script-auto-first",
    clientId: "client-mikes-auto",
    campaignId: "camp-mike-instant",
    title: "Auto Repair First Touch",
    type: "first-touch",
    content: "Hey {businessName}, I put together a quick idea for how your shop could turn more quote requests into booked repair jobs this month. Want me to send it over here?",
    category: "Auto Repair",
    niche: "Auto Repair",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "script-auto-follow",
    clientId: "client-mikes-auto",
    campaignId: "camp-mike-facebook",
    title: "Auto Follow-Up After No Reply",
    type: "follow-up",
    content: "Quick follow-up in case this got buried. I still have a couple of local content angles that could help {businessName} pull in more repair bookings.",
    category: "Auto Repair",
    niche: "Auto Repair",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "script-auto-objection",
    clientId: "client-mikes-auto",
    campaignId: "camp-mike-missed-calls",
    title: "Missed Call Recovery Script",
    type: "objection",
    content: "Saw a missed call come through and wanted to make sure you didn’t lose that job. I can help you build a follow-up system so missed calls turn into booked work instead of dead air.",
    category: "Operations",
    niche: "Auto Repair",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "script-realty-reactivation",
    clientId: "client-northstar-realty",
    campaignId: "camp-realty-reactivation",
    title: "Real Estate Reactivation",
    type: "reactivation",
    content: "Hey {name}, circling back because I had an idea for how your team could re-engage seller leads that went cold without sounding pushy. Want me to send it?",
    category: "Real Estate",
    niche: "Real Estate",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "script-detailing-offer",
    clientId: "client-zen-spa",
    campaignId: "camp-zen-brake-offer",
    title: "Detailing Offer Builder",
    type: "niche",
    content: "Your offer angle should package before-and-after content, local trust proof, and a simple monthly booking system into one offer that feels easy to say yes to.",
    category: "Car Detailing",
    niche: "Car Detailing",
    createdAt: now,
    updatedAt: now
  },
  {
    id: "script-ai-ranking",
    clientId: null,
    campaignId: null,
    title: "AI Hot Lead Ranking Prompt",
    type: "ai-generated",
    content: "Rank these leads by near-term close potential using stage, WhatsApp status, response recency, notes, and score. Return only the top 5 with a reason for each.",
    category: "AI",
    createdAt: now,
    updatedAt: now
  }
];

export const mockForms: FormDefinition[] = [
  {
    id: "form-mike-quote",
    clientId: "client-mikes-auto",
    campaignId: "camp-mike-instant",
    name: "Brake Quote Request",
    fields: [
      { id: "field-name", label: "Full Name", type: "text", required: true },
      { id: "field-phone", label: "Phone", type: "phone", required: true },
      { id: "field-service", label: "Service Needed", type: "textarea", required: true }
    ],
    defaultStage: "New",
    active: true,
    submissions: 42,
    conversionRate: 19,
    createdAt: now,
    updatedAt: now
  },
  {
    id: "form-realty-seller",
    clientId: "client-northstar-realty",
    campaignId: "camp-realty-reactivation",
    name: "Seller Consult Intake",
    fields: [
      { id: "field-owner", label: "Owner Name", type: "text", required: true },
      { id: "field-email", label: "Email", type: "email", required: true },
      { id: "field-city", label: "City", type: "text", required: true }
    ],
    defaultStage: "New",
    active: true,
    submissions: 18,
    conversionRate: 28,
    createdAt: now,
    updatedAt: now
  }
];

export const mockLeads: Lead[] = [
  {
    id: "lead-1000-islands",
    clientId: "client-mikes-auto",
    campaignId: "camp-mike-facebook",
    name: "1000 Islands Mobile Tire",
    businessName: "1000 Islands Mobile Tire",
    phone: "+1 613-555-0148",
    email: "",
    address: "Kingston, ON, Canada",
    city: "Kingston",
    niche: "Tire Shop",
    source: "CSV Import",
    whatsappStatus: "unknown",
    leadStage: "New",
    priority: "medium",
    tags: ["mobile-service", "tire"],
    notes: "Strong convenience angle. Could pitch local seasonal tire swap content and missed-call follow-up.",
    aiSummary: "Mobile tire service in Kingston. Good fit for convenience-focused offer and local service reels.",
    aiNextAction: "Check WhatsApp, then send a short message focused on emergency convenience and local trust.",
    score: 65,
    lastContactedAt: "",
    nextFollowUpAt: "2026-04-19T14:00:00.000Z",
    createdAt: "2026-04-17T11:00:00.000Z",
    updatedAt: now,
    previousMessages: []
  },
  {
    id: "lead-shanes-tire",
    clientId: "client-mikes-auto",
    campaignId: "camp-mike-instant",
    name: "Shane's Northern Tire",
    businessName: "Shane's Northern Tire",
    phone: "+1 204-201-3340",
    email: "",
    address: "Kenora, ON, Canada",
    city: "Kenora",
    niche: "Tire Shop",
    source: "Instant Form",
    whatsappStatus: "yes",
    leadStage: "Contacted",
    priority: "high",
    tags: ["quote-request", "hot"],
    notes: "Asked for a better way to turn inquiry traffic into appointments.",
    aiSummary: "High-intent instant form lead from a tire shop. Wants more booked appointments from existing attention.",
    aiNextAction: "Send a follow-up with one concrete booking-system angle and offer a 10-minute audit.",
    score: 88,
    lastContactedAt: "2026-04-17T12:30:00.000Z",
    nextFollowUpAt: "2026-04-18T12:30:00.000Z",
    createdAt: "2026-04-17T10:30:00.000Z",
    updatedAt: now,
    previousMessages: ["Sent first message about improving quote-to-booking flow."]
  },
  {
    id: "lead-zen-mobile",
    clientId: "client-zen-spa",
    campaignId: "camp-zen-brake-offer",
    name: "Zen Mobile Auto Spa",
    businessName: "Zen Mobile Auto Spa",
    phone: "+1 705-500-6042",
    email: "hello@zenmobile.example",
    address: "Kenora, ON, Canada",
    city: "Kenora",
    niche: "Car Detailing",
    source: "CSV Import",
    whatsappStatus: "yes",
    leadStage: "Interested",
    priority: "high",
    tags: ["visual-service", "offer"],
    notes: "Visual service. Offer should lean on before/after content and booked packages.",
    aiSummary: "Warm detailing lead with strong visual assets and clear service differentiation.",
    aiNextAction: "Send an offer framed around before/after reels and monthly package consistency.",
    score: 93,
    lastContactedAt: "2026-04-16T17:10:00.000Z",
    nextFollowUpAt: "2026-04-18T09:00:00.000Z",
    createdAt: "2026-04-16T15:00:00.000Z",
    updatedAt: now,
    previousMessages: ["Shared two before/after content concepts.", "Lead asked about trial pricing."]
  },
  {
    id: "lead-jaskaran",
    clientId: "client-northstar-realty",
    campaignId: "camp-realty-reactivation",
    name: "Jaskaran Singh",
    businessName: "Northstar Realty Group",
    phone: "+1 647-555-0192",
    email: "jaskaran@example.com",
    address: "Oakville, ON, Canada",
    city: "Oakville",
    niche: "Real Estate",
    source: "Reactivation",
    whatsappStatus: "yes",
    leadStage: "Replied",
    priority: "high",
    tags: ["seller-leads", "replied"],
    notes: "Replied after 2 days. Interested in consistent seller lead flow.",
    aiSummary: "Reactivated real estate lead who has already replied and wants consistent seller lead generation.",
    aiNextAction: "Follow up with a simple seller-intake offer and move toward a short discovery call.",
    score: 91,
    lastContactedAt: "2026-04-17T09:15:00.000Z",
    nextFollowUpAt: "2026-04-18T09:15:00.000Z",
    createdAt: "2026-04-15T14:00:00.000Z",
    updatedAt: now,
    previousMessages: ["Sent reactivation message.", "Lead replied asking how the system works."]
  },
  {
    id: "lead-brake-pro",
    clientId: "client-mikes-auto",
    campaignId: "camp-mike-missed-calls",
    name: "BrakePro Service Centre",
    businessName: "BrakePro Service Centre",
    phone: "+1 905-555-7721",
    email: "",
    address: "Mississauga, ON, Canada",
    city: "Mississauga",
    niche: "Auto Repair",
    source: "Missed Calls",
    whatsappStatus: "yes",
    leadStage: "Qualified",
    priority: "high",
    tags: ["missed-call", "qualified"],
    notes: "Very good fit. Mentioned losing weekend calls and wants a faster response flow.",
    aiSummary: "Qualified auto repair lead with urgent operations pain around missed calls and missed jobs.",
    aiNextAction: "Push to close with a concrete missed-call recovery system and short free trial.",
    score: 97,
    lastContactedAt: "2026-04-17T08:45:00.000Z",
    nextFollowUpAt: "2026-04-17T20:00:00.000Z",
    createdAt: "2026-04-14T12:00:00.000Z",
    updatedAt: now,
    previousMessages: ["Sent missed-call recovery idea.", "Lead asked about pricing and setup speed."]
  },
  {
    id: "lead-sold-realty",
    clientId: "client-northstar-realty",
    campaignId: "camp-realty-reactivation",
    name: "SoldWell Realty",
    businessName: "SoldWell Realty",
    phone: "+1 437-555-2288",
    email: "info@soldwell.example",
    address: "Toronto, ON, Canada",
    city: "Toronto",
    niche: "Real Estate",
    source: "Old CRM List",
    whatsappStatus: "no",
    leadStage: "Lost",
    priority: "low",
    tags: ["no-wa"],
    notes: "No WhatsApp and no reply on email. Low urgency.",
    aiSummary: "Low-priority real estate lead without WhatsApp. Not worth attention right now.",
    aiNextAction: "Deprioritize and move effort to warmer replied leads.",
    score: 31,
    lastContactedAt: "2026-04-10T10:00:00.000Z",
    nextFollowUpAt: "",
    createdAt: "2026-04-09T10:00:00.000Z",
    updatedAt: now,
    previousMessages: ["Sent initial email. No response."]
  },
  {
    id: "lead-pitstop",
    clientId: "client-mikes-auto",
    campaignId: "camp-mike-facebook",
    name: "Pitstop Auto Garage",
    businessName: "Pitstop Auto Garage",
    phone: "+1 519-555-3007",
    email: "",
    address: "London, ON, Canada",
    city: "London",
    niche: "Auto Repair",
    source: "Facebook Leads",
    whatsappStatus: "unknown",
    leadStage: "New",
    priority: "medium",
    tags: ["garage"],
    notes: "Likely good fit for content + booking stack.",
    aiSummary: "Fresh auto repair lead with likely WhatsApp-first potential.",
    aiNextAction: "Run WhatsApp check, then send a direct first-touch message.",
    score: 58,
    lastContactedAt: "",
    nextFollowUpAt: "2026-04-19T11:00:00.000Z",
    createdAt: "2026-04-17T15:40:00.000Z",
    updatedAt: now,
    previousMessages: []
  },
  {
    id: "lead-detailing-pro",
    clientId: "client-zen-spa",
    campaignId: "camp-zen-brake-offer",
    name: "Polished Finish Studio",
    businessName: "Polished Finish Studio",
    phone: "+1 289-555-4432",
    email: "owner@polishedfinish.example",
    address: "Burlington, ON, Canada",
    city: "Burlington",
    niche: "Car Detailing",
    source: "CSV Import",
    whatsappStatus: "yes",
    leadStage: "Won",
    priority: "high",
    tags: ["won", "detailing"],
    notes: "Converted. Using as model case for detailing outreach.",
    aiSummary: "Won detailing client. Strong proof point for the niche offer.",
    aiNextAction: "Use this account as proof and build a tighter case study around booked packages.",
    score: 99,
    lastContactedAt: "2026-04-15T13:00:00.000Z",
    nextFollowUpAt: "",
    createdAt: "2026-04-10T13:00:00.000Z",
    updatedAt: now,
    previousMessages: ["Closed after free trial pitch."]
  }
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: "activity-1",
    leadId: "lead-brake-pro",
    type: "ai",
    content: "AI suggested using a missed-call recovery offer with a free trial.",
    createdAt: "2026-04-17T08:50:00.000Z"
  },
  {
    id: "activity-2",
    leadId: "lead-jaskaran",
    type: "message",
    content: "Sent reactivation follow-up with seller lead system angle.",
    createdAt: "2026-04-17T09:15:00.000Z"
  },
  {
    id: "activity-3",
    leadId: "lead-shanes-tire",
    type: "whatsapp",
    content: "Marked as Has WhatsApp and moved to Contacted.",
    createdAt: "2026-04-17T12:35:00.000Z"
  },
  {
    id: "activity-4",
    leadId: "lead-pitstop",
    type: "import",
    content: "Imported from the Ontario auto CSV list.",
    createdAt: "2026-04-17T15:41:00.000Z"
  },
  {
    id: "activity-5",
    leadId: "lead-zen-mobile",
    type: "stage-change",
    content: "Moved from Replied to Interested after offer discussion.",
    createdAt: "2026-04-16T18:00:00.000Z"
  }
];
